optimizer:
  name: adam
  lr: 1.0e-4
  weight_decay: 0.0

train:
  epoch: 500
  batch_size: 4096
  s_batch: 2048
  save_model: true
  log_loss: true
  loss: pairwise # bpr
  test_step: 5 # evaluate per {test_step} epochs
  #pretrain_path: ./checkpoint/xxxx.pth
  reproducible: true
  seed: 2023
  tensorboard: true
  early_stop: true
  patience: 4
  

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20, 40] # top-k
  batch_size: 4096 # How many users per batch during validation

data:
  type: social # choose in {general_cf, multi_behavior, sequential, social}
  name: yelp

model:
  name: dsl # case-insensitive
  embedding_size: 64
  gnn_layer: 3
  uugnn_layer: 2
  dropout_rate: 0.5
  leaky: 0.5
  reg_weight: 1.0e-2
  soc_weight: 1.0e-2
  sal_weight: 1.0e-3

tune:
  enable: false # Whether to enable grid search to search for optimal hyperparameters
  hyperparameters: [gnn_layer, uugnn_layer] # The name of the hyperparameter
  gnn_layer: [1, 2, 3]
  uugnn_layer: [1, 2, 3]

