optimizer:
  name: adam
  lr: 1.0e-4 # not 1e-3
  weight_decay: 0

train:
  # trainer: kg_trainer
  epoch: 100
  batch_size: 1024
  kg_batch_size: 4096
  save_model: true
  loss: pairwise # bpr
  test_step: 1 # evaluate per {test_step} epochs
  #pretrain_path: ./checkpoint/xxxx.pth
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20] # top-k
  batch_size: 1024 # How many users per batch during validation

data:
  type: kg # choose in {general_cf, multi_behavior, sequential, social, kg}
  name: mind

model:
  name: kgcl # case-insensitive
  train_trans: false
  layer_num: 2
  decay_weight: 1.0e-5
  embedding_size: 64
  node_dropout: true
  node_dropout_rate: 0.5
  mess_dropout: true
  mess_dropout_rate: 0.1

tune:
  enable: false # Whether to enable grid search to search for optimal hyperparameters
  hyperparameters: [layer_num] # The name of the hyperparameter
  layer_num: [1, 2, 3] # Use a list to store the search range
