optimizer:
  name: adam
  lr: 1.0e-3 # not 1e-3
  weight_decay: 0

train:
  epoch: 100
  batch_size: 4096
  save_model: true
  loss: pairwise # bpr
  test_step: 3 # evaluate per {test_step} epochs
  #pretrain_path: ./checkpoint/xxxx.pth

test:
  metrics: [recall, ndcg] # choose in {ndcg, recall, precision, mrr}
  k: [10, 20, 40] # top-k
  batch_size: 1024 # How many users per batch during validation

data:
  name: yelp

model:
  name: lightgcn # case-insensitive
  keep_rate: 0.5
  layer_num: 2
  reg_weight: 1.0e-2
  embedding_size: 32

