optimizer:
  name: adam
  lr: 1.0e-4
  weight_decay: 1.0e-4

train:
  epoch: 300
  batch_size: 4096
  save_model: false
  loss: pairwise
  log_loss: false
  test_step: 3
  patience: 5
  reproducible: true
  seed: 2023

test:
  metrics: [recall, ndcg]
  k: [10, 20, 40]
  batch_size: 1024

data:
  type: general_cf
  name: gowalla

model:
  name: lightgcl
  dropout: 0
  layer_num: 2
  cl_weight: 1.0
  reg_weight: 1.0e-7
  temp: 0.5
  embedding_size: 32
  svd_q: 5

tune:
  enable: true
  hyperparameters: [layer_num, temp, cl_weight]
  layer_num: [2, 3]
  temp: [0.2, 0.5, 1]
  cl_weight: [0.1, 1, 2, 5]}
